### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by kobrin666** [mnickw/CycleTLS-dotnet#1]
hi. when i start i have some errors
PS D:\CycleTLS-dotnet-main\CycleTLS.ConsoleExample> dotnet run -r win-x64
C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1114,5): warning NETSDK117
9: при использовании "--runtime" требуется параметр "--self-contained" или "--no-self-contained". [D:\CycleTLS-dotnet-m
ain\CycleTLS.ConsoleExample\CycleTLS.ConsoleExample.csproj]
C:\Program Files\dotnet\sdk\6.0.402\Microsoft.Common.CurrentVersion.targets(5128,5): error MSB3030: не удалось скопиров
ать файл "D:\CycleTLS-dotnet-main\dist\index" - файл не найден. [D:\CycleTLS-dotnet-main\CycleTLS\CycleTLS.csproj]
C:\Program Files\dotnet\sdk\6.0.402\Microsoft.Common.CurrentVersion.targets(5128,5): error MSB3030: не удалось скопиров
ать файл "D:\CycleTLS-dotnet-main\dist\index.d.ts" - файл не найден. [D:\CycleTLS-dotnet-main\CycleTLS\CycleTLS.csproj]
C:\Program Files\dotnet\sdk\6.0.402\Microsoft.Common.CurrentVersion.targets(5128,5): error MSB3030: не удалось скопиров
ать файл "D:\CycleTLS-dotnet-main\dist\index-mac" - файл не найден. [D:\CycleTLS-dotnet-main\CycleTLS\CycleTLS.csproj]
C:\Program Files\dotnet\sdk\6.0.402\Microsoft.Common.CurrentVersion.targets(5128,5): error MSB3030: не удалось скопиров
ать файл "D:\CycleTLS-dotnet-main\dist\index.exe" - файл не найден. [D:\CycleTLS-dotnet-main\CycleTLS\CycleTLS.csproj]
C:\Program Files\dotnet\sdk\6.0.402\Microsoft.Common.CurrentVersion.targets(5128,5): error MSB3030: не удалось скопиров
ать файл "D:\CycleTLS-dotnet-main\dist\index.js" - файл не найден. [D:\CycleTLS-dotnet-main\CycleTLS\CycleTLS.csproj]

Ошибка сборки. Устраните ошибки сборки и повторите попытку.
PS D:\CycleTLS-dotnet-main\CycleTLS.ConsoleExample>

what can i do now? thanks

**Comment by mnickw** [comment]
Hi! Project is under development. You need files with the server written in golang. Do `npm install cycletls` in any folder, go to node_modules and copy `dist` folder to folder with CycleTLS solution. I'll update readme soon. You can chat with me in telegram @mnickw . (на русском, если надо)

**Comment by mnickw** [comment]
![dist](https://user-images.githubusercontent.com/57790664/199732140-0fea1439-867f-47c9-8505-82e24bb56663.png)

**Comment by mnickw** [comment]
Readme updated

**Comment by mnickw** [comment]
@kobrin666 напишите мне пожалуйста, есть пару вопросов по vfsglobal, может общими усилиями что-то сделаем

**Comment by kobrin666** [comment]
PS D:\CycleTLS-dotnet-main\CycleTLS.ConsoleExample> dotnet run -r win-x64
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: при использовании "--runtime" требуется параметр "--self-contained" или "--no-self-contained". [D:\CycleTLS-dotnet-main\CycleTLS.ConsoleExample\CycleTLS.ConsoleExample.csproj]
info: CycleTLS.CycleTLSClient[0]
      Websock: connecting, retry 0...
CycleTLS.CycleTLSResponse
2022/11/04 16:02:17 Socket Errorread tcp [::1]:9119->[::1]:52036: wsarecv: An existing connection was forcibly closed by the remote host.
PS D:\CycleTLS-dotnet-main\CycleTLS.ConsoleExample>

теперь вот так

**Comment by mnickw** [comment]
pull last version

**Comment by mnickw** [comment]
or you can replace
response to response.Body in program.cs
